"""updated models

Revision ID: 299445f87400
Revises: 54c04ee2a905
Create Date: 2024-10-05 19:34:23.254732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299445f87400'
down_revision = '54c04ee2a905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'price')
    # ### end Alembic commands ###
